<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'FavrMembers\\Vendor\\Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'FavrMembers\\Vendor\\FavrCore\\Admin\\FieldRenderer' => $vendorDir . '/favr/core/src/Admin/FieldRenderer.php',
    'FavrMembers\\Vendor\\FavrCore\\Fields\\FieldSet' => $vendorDir . '/favr/core/src/Fields/FieldSet.php',
    'FavrMembers\\Vendor\\FavrCore\\Fields\\Sanitizer' => $vendorDir . '/favr/core/src/Fields/Sanitizer.php',
    'FavrMembers\\Vendor\\FavrCore\\Support\\AssetVersion' => $vendorDir . '/favr/core/src/Support/AssetVersion.php',
    'FavrMembers\\Vendor\\FavrCore\\Support\\CsvFormat' => $vendorDir . '/favr/core/src/Support/CsvFormat.php',
    'FavrMembers\\Vendor\\FavrCore\\Support\\Hours' => $vendorDir . '/favr/core/src/Support/Hours.php',
    'FavrMembers\\Vendor\\FavrCore\\Support\\Template' => $vendorDir . '/favr/core/src/Support/Template.php',
);
