<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit3ffd5bdd9a33a4b482629fbf95970454
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('FavrMembers\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \FavrMembers\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit3ffd5bdd9a33a4b482629fbf95970454', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \FavrMembers\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit3ffd5bdd9a33a4b482629fbf95970454', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\FavrMembers\Vendor\Composer\Autoload\ComposerStaticInit3ffd5bdd9a33a4b482629fbf95970454::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
